# Generated by Django 3.0.5 on 2020-04-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0002_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('daily_space', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='price',
        ),
        migrations.AlterField(
            model_name='step',
            name='nutritioninfo',
            field=models.TextField(),
        ),
    ]
