# Generated by Django 3.0.5 on 2020-04-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_setp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setp',
            new_name='Step',
        ),
    ]
