# Generated by Django 3.0.5 on 2020-04-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toupee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_now', models.TextField(verbose_name='auto_now-add=True')),
                ('title', models.CharField(max_length=255)),
                ('times', models.TextField(verbose_name='1')),
            ],
        ),
    ]
