# Generated by Django 3.0.5 on 2020-04-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldbeans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toupee',
            name='time_now',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='toupee',
            name='times',
            field=models.TextField(),
        ),
    ]
