# Generated by Django 3.0.5 on 2020-04-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coldbeans', '0003_auto_20200417_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coldbean',
            old_name='times',
            new_name='description',
        ),
    ]
