# Generated by Django 3.0.5 on 2020-04-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coldbeans', '0004_auto_20200417_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coldbean',
            old_name='time_now',
            new_name='channel_up',
        ),
    ]
