# Generated by Django 3.0.5 on 2020-04-19 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coldbeans', '0005_auto_20200417_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coldbeans.Coldbean')),
            ],
        ),
    ]
