# Generated by Django 3.0.5 on 2020-04-20 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coldbeans', '0006_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='bean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coldbeans.Coldbean'),
        ),
    ]
